// Level 5 (Corporate IT) hardening guide content, keyed by diagram node id.
// 'l5' is the level-wide overview shown when the band label is clicked; the
// rest are per-component deep dives shown when a specific asset box is
// clicked. This app is meant to be used as a working reference while
// actually hardening a Level 5 environment, not just an explainer.
//
// Block shapes: { h } sub-heading, { p } paragraph, { list } bullet list,
// { code } monospace snippet (DNS/SPF/DMARC records), { links } a labeled
// list of external resources (real URLs where available, otherwise a
// search link built from the exact recommended search term).

const search = (q) => `https://www.google.com/search?q=${encodeURIComponent(q)}`;

export const LEVEL5_CONTENT = {
  l5: {
    blocks: [
      { h: 'Purdue Model Level Hardening' },
      { p: `This guide works through the Purdue Model level by level, moving from identifying malicious activity toward reducing the attack surface through preventive hardening. It proposes hardening measures that are cost-aware, operator-friendly and suitable for existing industrial environments, with particular attention to organizations that operate legacy systems, have limited maintenance windows and cannot immediately replace vulnerable equipment.` },
      { p: `Several open-source projects demonstrate how individual elements of an ICS hardening programme can be implemented, alongside the formal standards and guidance. The Awesome Industrial Control System Security repository catalogues CISA's Cyber Security Evaluation Tool, passive network-mapping tools, vendor-specific hardening scripts, protocol-analysis utilities, intrusion-detection projects and research testbeds. It shows both the maturity and the fragmentation of the tool landscape: many useful capabilities already exist, but are distributed across independent projects that must be selected, validated and integrated by the operator. It is used here as a source of implementation examples rather than as an authoritative standard.` },
      { p: `CISA's Cyber Security Evaluation Tool (CSET) provides a more structured assessment approach, guiding asset owners through evaluation of ICS and IT environments against recognized government and industry standards. It can support the baseline-assessment and gap-analysis stages of a hardening programme, identifying missing policies, architectural weaknesses and unimplemented controls. However, it is closer to a compliance checklist than to actual hardening, and mapping all assets in a program can be time-consuming. Future versions with AI integration that automatically map documented ICS architecture into the tool visually would be a meaningful improvement.` },
      { p: `An assessment result does not itself create a security control. Identifying an unrestricted communication path does not automatically modify the relevant firewall rule, and identifying excessive privileges does not remove them from an account. Findings must be translated into approved technical changes, tested against operational requirements and verified after implementation. CSET should therefore be viewed as an assessment and planning tool, not an enforcement mechanism.` },
      { p: `Passive network-mapping projects such as GRASSMARLIN illustrate how visibility can improve without intrusive active scanning, though the project has been archived since 2017 and carries an active CVE (CVE-2026-6807). Passive discovery is lower risk than active scanning, but does not by itself produce a complete inventory: devices that communicate infrequently, disconnected backups and isolated serial equipment may not appear during the observation window. Passive observation should be combined with switch configurations, firewall records, engineering documentation, controller project files, physical inspection and interviews with process owners to build an authoritative inventory of assets and permitted flows.` },
      { p: `Vendor-specific projects such as the PCS7 Hardening Tool enumerate security issues on Siemens PCS 7 DCS servers using checks derived from Siemens guidance. Such projects show that a general hardening framework must eventually be translated into configurations appropriate to the actual installed product. A generic recommendation such as "disable unnecessary services" does not identify which services a given SCADA/DCS platform actually requires: disabling one without understanding its dependencies could interrupt engineering, alarm, historian or operator functions. Vendor-specific checks must be reviewed against the installed product version, vendor documentation, support agreements and site operational requirements.` },
      { p: `A more recent community project, the ICS/IoT/OT Hardening Framework, attempts to combine asset discovery, Purdue Model visualization, protocol security analysis, firewall-rule generation, hardening, monitoring and compliance mapping in one workflow. It is treated here as an illustrative implementation, not an authoritative standard. Automatically generated firewall rules, compliance mappings, findings and hardening scripts must be independently reviewed, active scanning must be tested in an isolated environment or approved maintenance window, and vendor-support requirements considered before production changes. Open-source projects of this kind must also be vetted for trustworthy provenance, since newer projects may carry undisclosed weaknesses if built with heavy AI assistance. An integrated dashboard existing does not by itself prove every recommendation is safe, correct or suitable for a specific process.` },
      { p: `Open-source testbeds such as LICSTER and GRFICS allow segmentation policies, protocol attacks, IDS signatures, firewall rules and hardening changes to be evaluated without risking an operational process. LICSTER is particularly relevant to a cost-aware hardening approach: its authors report a working physical ICS security testbed built from open-source components for roughly €500. GRFICS provides a virtual industrial environment for demonstrating attacks and their physical-process effects, supporting testing of command injection, man-in-the-middle activity, protocol manipulation, segmentation and IDS rules. More flexible frameworks such as ICSSIM similarly allow customized virtual testbeds for investigating attacks and defensive controls. Such environments could support future empirical validation of this architecture: for example, reproducing the Level 5-to-Level 4 firewall policy virtually, generating attack traffic, and measuring the resulting IDS alerts and blocked communications, though no testbed can fully reproduce the timing constraints, proprietary software, hardware dependencies and safety requirements of every real installation.` },
      { p: `The proposed architecture does not depend on any single open-source project. These projects are used as implementation examples for capabilities derived from NIST SP 800-82, IEC 62443 and the documented ICS threat landscape, preventing a community-maintained tool from becoming the basis of a security requirement while still showing how a requirement might be implemented with existing or low-cost technology. Existing tools provide useful individual capabilities, including assessment, discovery, protocol analysis, hardening checks, detection and lab validation, but not, by themselves, a complete, cost-ranked, operator-oriented hardening plan for every Purdue level. This guide integrates those capabilities into a structured framework identifying what must be protected at each level, which controls are already achievable, which require investment, and how effectiveness can be verified.` },

      { h: 'Approach and Method' },
      { p: `The goal is deliberately modest. It does not try to design a perfect system, because almost no operator gets to build one. It works with the systems that already exist, with their legacy devices, plaintext protocols and limited budgets, and asks what can realistically be changed at each layer of the Purdue Model to reduce the attack surface. As noted at the Fortinet OT Cybersecurity Summit, decision makers rarely hear a security proposal as a security problem. They hear it as a question of risk, revenue and return on investment, and a measure that is unaffordable or requires unschedulable downtime will not be approved. Every control here is therefore chosen with cost in mind.` },
      { p: `The need for this guide follows from a gap in the literature: major standards clearly define the security objectives an OT environment should meet, but provide less guidance on implementing them where legacy equipment cannot be patched or replaced. IEC 62443 defines system security requirements and a structured approach to segmentation; NIST SP 800-82 Rev. 3 adapts the SP 800-53 control catalogue to OT. Both align with the NIST Cybersecurity Framework 2.0 and are increasingly reflected in regulation such as the NIS2 Directive. Research, meanwhile, has often addressed segmentation, protocol security and intrusion detection as separate topics, leaving operators to integrate the recommendations themselves. This guide brings these elements together into one layered approach to securing legacy OT environments.` },
      { p: `Controls were selected using three sources. The first is the standards baseline above, providing recognized control families and requirement language. The second is MITRE ATT&CK for ICS, whose techniques and mitigations are mapped back to documented ICS incidents, keeping the guidance threat-informed since a control is included because it counters an observed technique rather than because a generic checklist mentions it. The third is a cost-aware filter: each control is tagged configuration-only, open-source tool, or capital cost, with cheaper options presented first so an operator can act on no-cost measures immediately and defer expensive ones to a planned budget.` },
      { p: `This guide analyzes the Purdue Model top-down, from Level 5 (enterprise) to Level 0 (physical process), the reverse of the usual bottom-up presentation. There are three reasons for this order. First, it follows the path of a real attacker: in the most common intrusion sequence, the attack begins in IT and moves downward through the DMZ into supervisory and control layers, so hardening in the same order examines each layer as an intruder would actually try to cross it. Second, it moves from the familiar to the constrained: Levels 5 and 4 are ordinary enterprise IT, while the field levels carry the legacy hardware, plaintext protocols and real-time limits that make hardening hardest, so technical depth increases as this guide descends rather than front-loading it. Third, the descent ends at Level 0, the point where a successful attack stops being digital and becomes physical, and where available defenses are most limited. That is the right point for the analysis to culminate. This also mirrors a detection model in which signature-based detection sits near the enterprise boundary and specification-based detection sits at the field level.` },

      { h: 'Use of Artificial Intelligence in Hardening' },
      { p: `Artificial intelligence can support hardening by analysing inventories, firewall rules, configuration exports, vulnerability reports and security logs. It may help identify undocumented assets, excessive permissions, unusual communication paths, duplicate firewall rules and gaps against a security baseline, and can assist with drafting recommendations and correlating findings against NIST SP 800-82 and IEC 62443.` },
      { p: `AI-generated recommendations must not be applied automatically to production systems. A model may misunderstand an operational dependency, recommend disabling a required service, or generate an incorrect firewall rule. Every recommendation must be reviewed by an OT engineer, tested in a laboratory or maintenance window, and supported by a rollback procedure.` },
      { p: `Sensitive information must not be submitted to public AI services. This includes passwords, private keys, VPN configurations, network diagrams, PLC programs, firewall exports, vulnerability reports, internal IP addresses and vendor-access details. Where AI is used, data should be anonymized or processed through an approved private or locally hosted model, with access controls, logging, retention limits and contractual protections defined before operational data is processed.` },
      { p: `AI should be treated as a decision-support tool, not an autonomous administrator. It may accelerate analysis, but responsibility for approving and implementing changes remains with the system owner and the process engineer.` },

      { h: 'Role of Level 5 in the Purdue Model' },
      { p: `Level 5 represents the corporate IT environment at the top of the Purdue Model, containing the systems and services used across the organization rather than those directly responsible for managing production. Typical assets include central identity services (Active Directory or a cloud identity provider), corporate email, file storage, collaboration platforms, internet-facing applications, remote-access infrastructure, and employee workstations and laptops, and depending on the organization, security management, corporate backup and centralized monitoring platforms.` },
      { p: `Level 5 must be distinguished from Level 4, even though both belong to IT. Level 4 contains business systems more closely tied to operations: enterprise resource planning, production planning, maintenance management and logistics platforms. Level 5 provides organization-wide services supporting both Level 4 and the rest of the enterprise. A Level 4 production-planning application may depend on a Level 5 identity service to authenticate users, a corporate email system to distribute reports, and a remote-access service to support administrators. This dependency means a Level 5 compromise can indirectly weaken every level below it.` },
      { p: `In a correctly segmented Purdue architecture, Level 5 should not communicate directly with Levels 3, 2, 1 or 0. Information required by corporate users should pass through Level 4 and controlled interfaces at the IT/OT boundary, normally an industrial DMZ. Direct routes from employee workstations, corporate servers or internet-facing services to the control environment should not exist. This separation limits the effect of an ordinary IT compromise and must be enforced technically through firewalls, access-control rules and clearly defined conduits, not merely as a diagram or policy.` },
      { p: `Although Level 5 is furthest from the physical process, it remains highly important to ICS security because it is the most exposed part of the architecture. It communicates regularly with the public internet, cloud services, customers, suppliers and remote employees, processes email attachments, supports web browsing, and runs general-purpose operating systems with large numbers of applications. Attackers can gain an initial foothold here without understanding industrial processes or protocols at all.` },
      { p: `Identity infrastructure is especially important: Active Directory or another identity provider frequently controls access to workstations, servers, VPNs and business applications throughout the organization. A compromised privileged identity at Level 5 may provide access to Level 4 systems and, in poorly separated environments, to systems closer to the control network. Level 5 hardening must protect not only individual computers but the identities and trust relationships connecting the organization.` },
      { p: `Remote-access infrastructure creates another important connection to the lower levels. Employees, contractors and vendors may use VPNs, remote desktop or web-based support portals to connect from outside. This is legitimate, but it bypasses the physical distance that once helped protect industrial systems. Where one remote-access platform serves both enterprise and OT administration, a compromised Level 5 account may provide a direct path toward sensitive operational assets. Remote OT access should be separated from ordinary corporate remote access and mediated through controlled systems such as bastion hosts at an appropriate security boundary.` },
      { p: `A typical attack path begins with compromise of an employee account or workstation through phishing, credential theft, an exposed service or malware. The attacker establishes persistence, gathers information, and obtains more privileged credentials. From the initial Level 5 foothold, the attacker searches for connections to production-related systems at Level 4: shared accounts, administrative servers, file transfers, remote-management tools and trusted network routes. If boundaries are weak, the attacker continues toward the industrial DMZ and site operations network. This corresponds to the staged movement of the ICS Cyber Kill Chain and to ATT&CK for ICS techniques including External Remote Services, Valid Accounts and lateral movement through accessible services.` },
      { p: `Level 5 therefore has two roles in the proposed defense architecture. Its first role is preventive: reducing the probability of the initial enterprise foothold from which an ICS intrusion can develop. Its second role is containment: ensuring that compromise of an employee, account or corporate server does not automatically provide access to production systems. Strong identity management, secure remote access, endpoint hardening, network separation and centralized monitoring support both roles.` },
      { p: `Hardening Level 5 cannot by itself secure the industrial environment. An attacker may enter through a vendor connection, portable media, a Level 4 application or physical access to a lower-level device. Nevertheless, it provides the broadest opportunity to stop common attacks using mature, comparatively inexpensive IT security controls, and containing an intrusion here is generally less disruptive and costly than responding after the attacker has crossed into the operational environment.` },

      { h: 'Threat Landscape Summary' },
      { p: `Level 5 is exposed to most of the same threats as a conventional enterprise network: phishing, credential theft, vulnerable internet-facing services, malware and ransomware. In an industrial organization, however, the consequences differ. A compromised corporate account or workstation may become the first stage of an attack path toward Level 4 production-planning systems and, if architectural boundaries are weak, toward the operational environment below.` },
      { p: `The most important Level 5 threat is therefore not a single malware family or vulnerability, but the combination of an initial enterprise compromise, acquisition of trusted credentials, and abuse of legitimate connections between the enterprise and industrial environments. Attackers frequently avoid direct exploitation of industrial protocols until they have a stable foothold, using the time inside the organization to collect information, identify administrators and engineers, steal credentials, study the architecture and locate systems that provide access to lower Purdue levels. See the Internet, Web Servers, Email, Authentication, Desktops, File Servers and Databases nodes on this level for the specific techniques, incidents and controls addressing each part of this chain.` },
      { p: `A representative Level 5 attack path can be summarized as: spear-phishing email or vulnerable external service → compromise of a corporate workstation or account → credential theft and privilege escalation → access through VPN, RDP or another trusted service → discovery of Level 4 systems and shared infrastructure → lateral movement through valid accounts or vulnerable services → access to an OT-facing jump host, historian or dual-homed system → attempted movement toward the industrial control environment.` },
      { p: `Ukraine 2015 followed this general sequence: spear phishing created the initial enterprise foothold, credential collection and reconnaissance prepared later stages, valid accounts and remote services enabled movement toward grid-operator systems, and destructive tools delayed recovery. Colonial Pipeline demonstrated the operational consequences of weak remote-access and account controls, while NotPetya showed how vulnerable services, shared credentials and insufficient segmentation let destructive malware spread across enterprise and industrial-supporting environments.` },
      { p: `These incidents show that Level 5 hardening must perform two functions. It must reduce the probability of initial compromise through phishing, exposed services, removable media and malware, and it must prevent a successful corporate intrusion from crossing into Level 4. The second function matters most, because no organization can guarantee that every malicious email, stolen password or software vulnerability will be prevented. Strong identity separation, controlled remote access, patch management, least functionality and enforceable segmentation are what turn a Level 5 compromise into a contained IT incident rather than the beginning of an operational disruption.` },

      { h: 'Capital-Cost Improvements: Prioritization' },
      { p: `Configuration-only controls and open-source monitoring provide a strong baseline, but do not address every risk. Larger or more exposed organizations may require commercial technologies for stronger automation, centralized governance, vendor support and continuous analysis. These require procurement and should be justified through risk reduction, operational impact and expected return on investment, not used to replace basic security administration. Purchasing an advanced platform provides limited value while dormant accounts remain active, MFA is unenforced, or networks remain flat; capital-cost improvements should follow, not precede, the configuration baseline. Specific capital investments (PAM, EDR/XDR, email security gateways, OT-aware remote access, security-awareness training) are detailed under their respective component nodes on this level.` },
      { p: `Capital expenditure should be prioritized according to the attack paths actually observed. An organization suffering repeated identity misuse gains more from PAM and phishing-resistant authentication than from another network appliance; one with limited endpoint visibility should prioritize EDR; one heavily dependent on vendor maintenance should prioritize an OT-aware remote-access platform. Return on investment should weigh avoided downtime, incident-response cost, regulatory exposure, recovery effort and potential safety consequences. In industrial environments, preventing one operational shutdown may justify several years of security investment, but expected value must be evaluated honestly, including licence costs, integration, training, staffing and the possibility that a product is purchased but never properly operated.` },
      { p: `Configuration-only hardening provides a high return because it removes common attack paths using systems the organization already owns. The recommended order is: map the environment, protect privileged and remote identities, remove obsolete accounts and services, restrict endpoint execution, narrow network communication, and strengthen email authentication. These measures do not eliminate all risk, but make it considerably harder for a Level 5 compromise to spread toward Level 4.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Run a baseline gap assessment (for example CISA CSET) against NIST SP 800-82 and IEC 62443',
        'Map each planned control to a MITRE ATT&CK for ICS technique seen in real incidents',
        'Tag every control as configuration-only, open-source tool, or capital cost',
        'Define an AI policy: no sensitive OT data submitted to public AI services',
        'Require human review of AI-generated configurations before applying them',
        'Follow the implementation order: map, protect identities, remove obsolete access, restrict endpoints, narrow the network, strengthen email',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'NIST SP 800-82 Rev. 3, OT security control baseline', url: 'https://csrc.nist.gov/pubs/sp/800/82/r3/final' },
        { label: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
        { label: 'IEC 62443 series', url: search('ISA IEC 62443 series') },
        { label: 'MITRE ATT&CK for ICS matrix', url: 'https://attack.mitre.org/matrices/ics/' },
        { label: 'MITRE ATT&CK Enterprise matrix', url: 'https://attack.mitre.org/' },
        { label: 'CISA Cyber Security Evaluation Tool (CSET)', url: search('CISA CSET download') },
      ] },
    ],
  },

  internet: {
    blocks: [
      { h: 'AI-Assisted Attack Activity' },
      { p: `Artificial intelligence can reduce the effort required to conduct attacks against Level 5. Attackers may use generative AI to produce convincing spear-phishing messages, translate fraudulent communications, summarize stolen technical documents, identify vulnerable software and automate reconnaissance, as well as to modify scripts and malware so they better match the target environment.` },
      { p: `This does not create a wholly new attack path; it increases the speed, scale and quality of existing techniques such as spear phishing, credential theft, vulnerability exploitation and lateral movement. The controls proposed throughout this level, including MFA, attachment filtering, application allowlisting, patching, segmentation and centralized monitoring, remain relevant, but defenders should expect more convincing social engineering and faster analysis of stolen ICS documentation. AI-generated content should not automatically be trusted by operators or administrators: configuration commands, scripts and incident-response recommendations produced by an AI system must be verified before execution, particularly when they affect remote access, firewalls, identity infrastructure or systems connected to Level 4.` },

      { h: 'Asset & Exposure Inventory' },
      { p: `A Level 5 hardening programme should begin with a complete map of the existing infrastructure. Security controls cannot be applied consistently when the organization does not know which devices, identities, services and communication paths exist. The initial inventory should include corporate workstations and servers, Active Directory or cloud identity tenants, privileged accounts, remote-access gateways, email systems, internet-facing services, network segments, firewall rules and every system that exchanges information with Level 4.` },
      { p: `The map should show not only physical and virtual assets but trust relationships. An organization may know it owns a server while remaining unaware that it uses a shared administrative account, accepts RDP from the entire corporate network, or can communicate directly with a production-management system. These relationships are often more important to an attacker than the device itself.` },
      { p: `The inventory should be compared with external exposure information using the organization's own firewall and DNS records and, where appropriate, public exposure search engines such as Shodan. For example, an operator may discover that an old VPN appliance, Citrix gateway or test web server remains publicly reachable years after the project it was installed for ended. Shodan should be used only to examine assets owned or explicitly authorized by the organization. It should not replace an internally maintained inventory. A CISA CSET baseline assessment is a useful companion here, mapping gaps against recognized standards rather than just exposure.` },

      { h: 'DNS Filtering (Protective DNS)' },
      { p: `Outbound DNS resolution should be directed through a controlled resolver that can block known-malicious, newly registered and uncategorized domains. Protective DNS is a low-cost configuration measure because it uses infrastructure the organization already operates and can interrupt malware that relies on domain lookups for command-and-control or payload retrieval. It complements behavioural DNS monitoring: filtering blocks known-bad lookups proactively, while monitoring identifies suspicious patterns that filtering alone would miss.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Build a complete inventory of internet-facing services, identities and firewall rules',
        'Document trust relationships (shared accounts, RDP paths), not only devices',
        'Verify owned assets in Shodan and reconcile against firewall and DNS records',
        'Decommission or firewall exposed systems left over from finished projects',
        'Route outbound DNS through a filtering resolver that blocks malicious domains',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Shodan, check your own internet-exposed services', url: 'https://www.shodan.io' },
        { label: 'CISA CSET download', url: search('CISA CSET download') },
        { label: 'Quad9, free protective/filtering DNS resolver', url: 'https://www.quad9.net' },
      ] },
    ],
  },

  web: {
    blocks: [
      { h: 'Unpatched and Legacy Services' },
      { p: `Internet-facing and internal enterprise services represent an important attack path: obsolete VPN appliances, unsupported web applications, old Windows servers, unmaintained file-sharing services and remote administration products. Attackers routinely scan the public internet for known vulnerabilities and exposed management interfaces, then repeat the process against internal systems once inside.` },
      { p: `This attack path maps to Exploit Public-Facing Application, T1190 in Enterprise ATT&CK and T0819 in ATT&CK for ICS. Exploitation of vulnerable services during lateral movement maps to Enterprise T1210 and ICS T0866. Directly exposed industrial or OT-adjacent devices may also be represented by Internet Accessible Device, T0883.` },
      { p: `Patching is less difficult at Level 5 than at lower Purdue levels because corporate services generally tolerate scheduled maintenance more easily than controllers or safety systems. Level 5 should therefore have a mature vulnerability and patch-management process. Unsupported operating systems and services should be replaced, isolated or protected by compensating controls, and systems that cannot immediately be patched should not remain directly exposed to the internet. They should sit behind tightly configured firewalls or application gateways.` },
      { p: `Patching alone is not sufficient. Organizations must maintain an accurate inventory of internet-facing systems, software versions and responsible owners; unused applications, protocols and listening services should be removed under the principle of least functionality. Emergency patching should prioritize vulnerabilities that are actively exploited, reachable from the internet, or present on systems that provide administrative access toward Level 4.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Maintain an inventory of internet-facing systems with software versions and owners',
        'Patch internet-facing servers and remote-access appliances with the highest priority',
        'Replace, isolate or protect unsupported operating systems and services',
        'Move systems that cannot be patched behind tightly configured firewalls or gateways',
        'Remove unused applications, protocols and listening services (least functionality)',
        'Fast-track patches for actively exploited, internet-reachable vulnerabilities',
      ] },
    ],
  },

  email: {
    blocks: [
      { h: 'Spear Phishing' },
      { p: `Spear phishing is a targeted form of social engineering in which an attacker sends an email designed for a specific person, department or organization, often imitating a supplier, manager, government institution or trusted business partner. It commonly contains a malicious attachment (Office document, PDF, compressed archive) or directs the victim to a credential-harvesting website.` },
      { p: `MITRE ATT&CK for ICS classifies malicious email attachments as Spearphishing Attachment, T0865; the equivalent Enterprise sub-technique is T1566.001. These attacks normally depend on the user opening the file and enabling its malicious content. Successful execution can install a remote-access tool, downloader or credential-stealing program on the Level 5 workstation.` },
      { p: `The 2015 attack against the Ukrainian power grid shows how an ordinary enterprise phishing attack can begin a far more serious industrial intrusion. Attackers delivered malicious Office documents to employees of electricity distribution companies, installing BlackEnergy malware and providing an initial corporate foothold. The attackers then conducted reconnaissance, collected credentials and gradually moved toward the systems used to operate the electricity distribution network.` },
      { p: `Spear phishing targets the part of the Purdue architecture where email and internet access are expected and cannot simply be removed, so the control objective is to reduce the probability that a malicious message reaches a user and to limit what happens if the user opens it. Relevant measures include attachment filtering, sender-authentication controls, endpoint protection, disabling unnecessary Office macros, restricting script execution and training users to recognize suspicious requests.` },

      { h: 'Email Security Controls' },
      { p: `Email remains a common route for spear phishing, malware delivery, impersonation and credential theft. Several important protections can be enabled through DNS and mail-platform configuration alone.` },
      { h: 'Sender Policy Framework (SPF)' },
      { p: `SPF publishes which systems are authorized to send email for the organization's domain. If, for example, the organization sends mail only through Microsoft 365 and one approved marketing provider, the SPF record should list only those sources:` },
      { code: 'v=spf1 include:spf.protection.outlook.com -all' },
      { p: `Only one SPF record should be published per domain, and every legitimate sender must be incorporated. SPF alone does not prevent all impersonation because it validates the envelope sender rather than the address displayed to the user.` },
      { h: 'DomainKeys Identified Mail (DKIM)' },
      { p: `DKIM adds a cryptographic signature to outgoing messages; receiving systems use a public key published in DNS to verify the message was signed by an authorized mail service and not modified after signing. A concrete implementation enables DKIM signing for the primary corporate domain in Microsoft 365 or Google Workspace, publishes the required selector records in DNS, and verifies outgoing messages carry a valid DKIM result. Keys and selectors should be rotated per platform guidance.` },
      { h: 'DMARC' },
      { p: `DMARC combines SPF and DKIM with alignment to the visible From domain, and lets the domain owner specify how receiving systems should treat messages that fail authentication. Deployment should be gradual. An organization may first publish:` },
      { code: 'v=DMARC1; p=none; rua=mailto:dmarc-reports@example.com' },
      { p: `The resulting reports identify legitimate and unauthorized senders. After all approved systems are aligned, policy can move to p=quarantine and later p=reject; moving directly to rejection without identifying all legitimate third-party services can block valid mail. For example, DMARC reports might reveal that a payroll provider sends messages using the corporate From address without passing aligned SPF or DKIM. The provider must be configured correctly before enforcement.` },
      { h: 'Attachment and Content Filtering' },
      { p: `High-risk attachments should be blocked, quarantined or delivered only through controlled workflows. Examples include executable files, scripts, shortcut files, disk images and password-protected archives that cannot be inspected. A basic policy may block .exe, .scr, .js, .vbs, .lnk, .iso and .img files and quarantine Office documents containing macros that originate outside the organization. Departments with a legitimate need for a blocked format should use an approved file-transfer service rather than weakening the rule for all users. Filtering should also inspect links and detect display-name impersonation where the mail platform supports it. For example, a message displaying the chief executive's name but originating from an unrelated external domain can be marked with an external-sender warning or quarantined.` },

      { h: 'Capital Investment: Email Security Gateways' },
      { p: `Commercial email security gateways add advanced phishing, malware and impersonation protection beyond standard SPF, DKIM, DMARC and attachment rules: attachment sandboxing, URL rewriting, business-email-compromise detection, natural-language analysis and post-delivery removal. For example, a malicious Office document with no known malware signature can be opened in a sandbox that observes it launching a script and contacting an external server, blocking the attachment before delivery.` },
      { p: `The expected return is fewer successful phishing and malware infections. This matters because email is a common initial-access route. Operational concerns include false positives, delayed message delivery, privacy considerations and dependency on an external cloud provider.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Publish one SPF record listing every legitimate sender, ending in -all',
        'Enable DKIM signing and publish selector records; rotate keys per platform guidance',
        'Deploy DMARC at p=none with report collection',
        'Move DMARC to quarantine and then reject after aligning all legitimate senders',
        'Block high-risk attachment types (.exe, .scr, .js, .vbs, .lnk, .iso, .img)',
        'Quarantine externally sourced Office documents containing macros',
        'Enable link inspection and display-name impersonation detection',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Configure SPF for Microsoft 365 / Google Workspace', url: search('configure SPF Microsoft 365 Google Workspace') },
        { label: 'Enable DKIM signing for Microsoft 365 / Google Workspace', url: search('enable DKIM Microsoft 365 Google Workspace') },
        { label: 'DMARC.org, deployment guidance and reporting', url: 'https://dmarc.org' },
        { label: 'Exchange Online Protection anti-malware policy', url: search('Exchange Online Protection anti-malware policy') },
        { label: 'Cloud email security gateway comparison', url: search('cloud email security gateway') },
      ] },
    ],
  },

  auth: {
    blocks: [
      { h: 'Credential Theft, Password Reuse & Valid Accounts' },
      { p: `Once an attacker compromises a Level 5 endpoint, credential theft is commonly the next objective. Credentials may be extracted from browser password stores, operating-system memory, cached sessions, configuration files, remote-management tools or poorly protected password databases, or obtained through fake login pages or purchased breach dumps.` },
      { p: `Password reuse increases this risk: an employee may use the same or a similar password for a personal account, corporate email, a VPN and a remote administration service, so a breach of one service exposes the others. Dormant accounts are particularly dangerous because their misuse may not be noticed quickly.` },
      { p: `MITRE ATT&CK for ICS describes use of compromised or default credentials as Valid Accounts, T0859 (Enterprise T1078), letting attackers bypass access controls and make malicious activity resemble legitimate administration. Password reuse and testing of breached credentials maps to Credential Stuffing, T1110.004; extraction of credentials from an operating system maps to OS Credential Dumping, T1003.` },
      { p: `The danger increases when credentials and administrative privileges overlap between Level 5, Level 4 and OT-facing systems. A corporate domain administrator should not automatically hold administrative rights over historians, jump servers or engineering workstations. Reusing the same account across these environments creates a direct trust path: an attacker who compromises one identity can move between systems without exploiting a new vulnerability.` },
      { p: `Colonial Pipeline provides an important example. Public investigations reported that attackers entered through an inactive VPN account whose password had been compromised and was not protected by MFA. The ransomware affected the corporate environment rather than directly manipulating pipeline controllers, yet the company halted pipeline operations because it could not immediately exclude wider compromise and because business functions required for operation, including billing, were disrupted. A Level 5 identity failure can therefore create a major physical-service disruption even without confirmed access to the control network.` },

      { h: 'Identity and Access Management' },
      { p: `Identity and access management is the highest-priority configuration area because valid accounts can let an attacker bypass many perimeter controls. Existing logged-in sessions should be checked as part of this review.` },
      { h: 'Multi-Factor Authentication' },
      { p: `MFA should be enforced for externally accessible services, privileged accounts, cloud email, VPN connections, remote desktop gateways and administration portals. For limited budgets, TOTP phone apps (Microsoft Authenticator, Google Authenticator, FreeOTP or another standards-compatible authenticator) are a practical alternative to hardware tokens. Consider a maintenance engineer connecting to the VPN with only a username and password: if those credentials are exposed in a phishing campaign, the attacker can authenticate from elsewhere without a technical barrier. Requiring a password plus a rotating authenticator code means the stolen password alone is insufficient. MFA should first cover domain administrators, VPN users, email administrators, backup administrators and accounts able to reach Level 4 systems. Authenticator apps are a large improvement over passwords alone, but one-time codes remain vulnerable to real-time phishing. Where supported, phishing-resistant methods such as FIDO2 keys, passkeys or certificate-based authentication offer stronger protection.` },
      { h: 'Dormant Account Removal' },
      { p: `Accounts belonging to former employees, expired contractors, retired applications and completed projects should be disabled promptly and later deleted per retention requirements. A common failure is an employee leaving while their AD, email and VPN accounts remain active because HR and IT offboarding are not connected, for example a contractor added to "VPN Users" and "Server Administrators" for a six-month deployment whose account still exists two years later with no active owner. A monthly report of accounts with no successful login for 90 or 180 days provides a starting point; accounts should be validated with their business owners, disabled, removed from privileged groups and monitored before final deletion. Service accounts must be handled separately. They may go months without an interactive login while still supporting an operational application, so should be documented (owner, purpose, dependent systems, permitted login type) rather than deleted merely for appearing inactive.` },
      { h: 'Least-Privilege Permissions' },
      { p: `Users should receive only the permissions their responsibilities require, granted through role-based groups rather than directly to individuals, making access easier to audit and remove on role change. A finance employee needing read access to monthly production reports should get a read-only reporting group, not membership in a broad server-administrator group; a desktop-support technician may need local admin on user workstations but not rights over domain controllers, backup servers or Level 4 applications. Least privilege should also apply to applications and service accounts. A reporting service that only reads from a database should not use a database-owner account, and a scheduled task that copies one file should not run as a domain administrator.` },
      { h: 'Restriction of Domain Administrator Accounts' },
      { p: `Membership in highly privileged groups (Domain Admins, Enterprise Admins, Schema Admins) should be kept to the smallest possible number and never used for email, browsing or daily office activity. Administrators should have a normal account for routine work and a separate privileged account for approved administrative actions: for example, ana.ristovska for email/office applications and adm-ana.ristovska for server administration, with the privileged account denied interactive login on ordinary workstations and used only from a hardened administration device or jump host. Temporary membership in highly privileged groups is preferable to permanent assignment where the directory platform supports it, and old group memberships should be reviewed regularly to catch privilege accumulation from past roles.` },
      { h: 'Leaked-Credential Detection' },
      { p: `Organizations should assume some employee credentials will eventually appear in breach databases, infostealer logs or phishing collections. Exposure-monitoring services such as Hudson Rock can identify credentials and devices associated with infostealer infections; Have I Been Pwned and identity-platform risk detections can support password-exposure checks. These are intelligence sources, not proof of active misuse. A concrete response workflow: validate the affected identity belongs to the organization, reset the password, revoke active sessions and tokens, enforce MFA, examine login records, check the endpoint for infostealer malware, and determine whether the password was reused on VPN or administrative systems. Passwords should never be manually entered into untrusted public websites; automated breached-password checks should use privacy-preserving mechanisms or approved enterprise services.` },

      { h: 'Capital Investment: Privileged Access Management (PAM)' },
      { p: `PAM platforms control, monitor and audit high-value administrative credentials: password vaulting, automatic rotation, approval workflows, just-in-time privilege, session proxying and recording. A shared local administrator password used across multiple Level 5 servers means one compromise can expose all of them; a PAM platform can store a unique password per server, rotate it automatically, and release it only to an approved administrator for a limited period. PAM is particularly valuable for vendor and service accounts. Rather than a permanent vendor password, the organization approves a temporary session without disclosing the underlying credential, which can be logged or recorded for review. Expected return: lower probability of privilege abuse, reduced password reuse, faster revocation and stronger audit evidence. Operational impact: integration effort, changed administrator workflows, and the risk that an unavailable PAM service delays emergency maintenance. High-availability design and documented break-glass access are necessary.` },

      { h: 'External Remote Services (Threat)' },
      { p: `Remote-access services are a major entry point because they are intentionally exposed beyond the internal network: VPN concentrators, Citrix services, remote desktop gateways, cloud administration portals, vendor-support platforms. MITRE ATT&CK for ICS classifies this as External Remote Services, T0822 (Enterprise T1133). Engineers and vendors may need to maintain geographically remote sites, but the problem arises when remote access is permanently enabled, protected only by a password, shared between users, or connected too directly to operational assets. Split tunnelling and unmanaged vendor laptops can create an additional bridge between an external network and the internal environment.` },
      { p: `The Ukraine attackers used credentials taken from the Windows domain environment to access a VPN used by grid operators; MITRE also records valid accounts being used to move through VPN connections and dual-homed systems to reach employee workstations hosting HMI applications. This demonstrates that a VPN does not itself provide security when an attacker already possesses an accepted account. It encrypts and transports the attacker's session the same way it transports a legitimate user's session. External remote access should therefore be concentrated through a small number of managed gateways rather than permitted directly to individual internal systems, require phishing-resistant MFA where possible, use individually assigned accounts, and be enabled only for the duration of an approved maintenance activity. Direct remote desktop or VPN connections from the internet to an HMI, historian, engineering workstation or controller should never be permitted.` },

      { h: 'Secure Remote Access for Employees and Vendors' },
      { p: `Remote access deserves separate treatment because it recurs in major incidents and creates an intentional pathway through the network perimeter. Colonial Pipeline showed that compromise of a legacy VPN account without MFA can contribute to disruption of critical services even without confirmed direct manipulation of controllers. The objective is not to eliminate remote access. Modern industrial organizations depend on remote employees, centralized support teams, equipment manufacturers and specialist contractors, but the goal is to ensure it is individually attributable, limited in scope, temporary where possible, and monitored.` },
      { h: 'VPN Hardening' },
      { p: `VPN gateways should run currently supported software, strong cryptographic protocols and trusted certificates. Obsolete protocols and weak cipher suites should be disabled, and the appliance should be in the organization's high-priority patch cycle because it is directly internet-exposed. Access should be assigned through groups based on business need. A successful login should not grant unrestricted routing to all internal networks. For example, a remote employee may need email, document management and an ERP portal; a network engineer may need only a management bastion host; a vendor may need only one support server. These three should not share the same VPN profile. Authentication logs should record user, source address, device, time, authentication method and assigned network access, with alerts for repeated failures, impossible travel, disabled-account use and logins outside approved maintenance windows.` },
      { h: 'Multi-Factor Authentication (Remote Access)' },
      { p: `All remote access should require MFA. Password-only access is insufficient because passwords are phished, reused, stolen by infostealers and exposed in breaches. Application-based OTP is a reasonable minimum where stronger methods are unavailable; phishing-resistant methods should be preferred for administrators and vendors with access toward Level 4, and SMS should not be the preferred method where an authenticator app, passkey, certificate or hardware key is available. Emergency or break-glass accounts should be limited, monitored and tested. They are not a convenient way to bypass MFA during normal work.` },
      { h: 'Bastion Hosts' },
      { p: `A bastion host is a specialized, hardened server deliberately exposed to an untrusted network (the internet or corporate IT) that serves as the only gateway through which authorized users reach a private, highly sensitive internal network. Remote users should connect first to a hardened bastion or jump host rather than directly to internal servers, which becomes the controlled point from which authorized administration is performed. For example, a vendor connects via VPN with MFA and reaches a bastion in the industrial DMZ; from there, firewall rules permit access only to the specific Level 4 application server under maintenance, and direct routing from the vendor laptop to Level 4 or lower levels is blocked. The bastion should have a limited software set, application allowlisting, endpoint monitoring, session timeout, and no ordinary email or browsing function; file transfer should be disabled by default or scanned. A bastion provides no protection if users can bypass it. Network rules must ensure direct RDP, SSH or vendor-protocol access from remote-access pools to protected systems is not possible.` },
      { h: 'Time-Limited and Approved Access' },
      { p: `Vendor and high-risk remote access should be disabled by default and activated only for an approved maintenance period, expiring automatically rather than depending on an administrator remembering to remove it. A concrete workflow:` },
      { list: [
        'The system owner submits a maintenance request',
        'The request identifies the vendor, target system, purpose and time window',
        'An authorized manager approves the request',
        'The account or access rule is enabled shortly before the window',
        'The user connects through MFA and the bastion',
        'The session is logged',
        'Access expires automatically',
        'The system owner confirms the work is complete',
      ] },
      { p: `This reduces the number of permanently usable external accounts and creates evidence of who approved each connection.` },
      { h: 'Vendor Account Management' },
      { p: `Every external person should have an individually assigned account. Shared accounts such as vendor, support or admin make accountability impossible and allow access to continue after a team member changes roles. Vendor accounts should have an identified internal sponsor, an expiration date and a documented target system, reviewed periodically and disabled when the contract ends. Device requirements should also be defined: a vendor connecting from an unmanaged laptop also used for email, personal browsing and other customers is a significant risk. Where possible, access should require an approved device, current patches, endpoint protection and a supported OS, with higher-risk vendors required to use a virtual desktop or browser-isolated access method rather than connecting their device directly. Contracts should require incident notification, credential protection, subcontractor control and cooperation with logging and investigation.` },
      { h: 'Session Logging and Monitoring' },
      { p: `Remote sessions should generate centralized authentication and network logs; high-risk administrative sessions should also be recorded where legally and operationally appropriate. Session recording is especially useful for vendor access, providing evidence of commands executed, files transferred and configuration changes. Users must be informed of monitoring, and recordings must be protected from unauthorized access. Alerts should identify:` },
      { list: [
        'Connections outside approved time windows',
        'Access to systems outside the assigned scope',
        'Large file transfers',
        'Disabled logging',
        'Use of command-line tools not expected for the maintenance task',
        'Multiple simultaneous sessions from one account',
        'Connections from unexpected countries or networks',
        'Attempts to move from the bastion to additional systems',
      ] },
      { p: `Logging must be paired with review. Recording thousands of sessions that nobody examines provides limited security value.` },
      { h: 'Emergency Access and Operational Continuity' },
      { p: `Remote-access controls must account for emergency maintenance. A process that is too slow may encourage engineers to create informal bypasses, so the organization should establish an emergency approval path that is faster than the normal process but still requires individual authentication, MFA and retrospective review. Dependence on remote access also creates an availability risk. If the VPN, identity provider or bastion fails during an incident, authorized personnel may be unable to support operations, so redundant access infrastructure and tested local procedures may be necessary for critical sites.` },
      { p: `Secure remote access combines identity, network segmentation and monitoring. The strongest design is an MFA-protected connection to a managed gateway, followed by access through a monitored bastion to a specifically authorized target for a limited time. Direct internet access to HMIs, historians, engineering workstations and controllers should never be permitted. This reduces the probability that stolen employee or vendor credentials give an attacker a direct path from Level 5 into the operational environment.` },

      { h: 'Capital Investment: OT-Aware Remote-Access Platforms' },
      { p: `Industrial organizations frequently require vendors and engineers to access geographically remote systems, and general-purpose VPN access often provides more network reach than needed. OT-aware remote-access platforms can provide identity-based access to a specific asset or application through a controlled gateway, with MFA, device validation, approval workflows, time-limited access, protocol proxying, session recording and separation between the vendor endpoint and the target network. For example, a pump-system vendor may be granted access only to a designated maintenance server for two hours during an approved window, unable to scan the rest of the network, with the complete session recorded. Expected return: lower third-party risk, improved accountability, reduced probability that a compromised vendor account becomes an unrestricted network entry point. Operational impact: gateway deployment, integration with existing systems, and possible resistance from vendors accustomed to unrestricted VPN access.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Enforce MFA on VPN, remote desktop gateways, cloud email and admin portals',
        'Prefer phishing-resistant MFA (FIDO2 keys, passkeys) for administrators',
        'Disable dormant accounts after a 90 or 180 day inactivity review',
        'Document owner and purpose for every service account',
        'Grant permissions through role-based groups, never direct assignment',
        'Keep Domain Admins minimal; separate admin accounts from daily accounts',
        'Deny privileged accounts interactive login on ordinary workstations',
        'Monitor breach and infostealer sources for leaked employee credentials',
        'Route all vendor remote access through an MFA gateway and monitored bastion',
        'Disable vendor accounts outside approved maintenance windows',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Microsoft Authenticator', url: search('Microsoft Authenticator app') },
        { label: 'Google Authenticator', url: search('Google Authenticator app') },
        { label: 'FreeOTP, open-source authenticator', url: search('FreeOTP') },
        { label: 'FIDO Alliance, FIDO2 keys and passkeys', url: 'https://fidoalliance.org' },
        { label: 'Have I Been Pwned, breach exposure lookup', url: 'https://haveibeenpwned.com' },
        { label: 'Hudson Rock, infostealer credential exposure', url: search('Hudson Rock infostealer') },
        { label: 'Privileged access management platforms', url: search('privileged access management') },
        { label: 'OT-aware remote access platforms', url: search('OT remote access platform') },
      ] },
    ],
  },

  desktops: {
    blocks: [
      { h: 'Malware and Ransomware' },
      { p: `Level 5 workstations and servers run general-purpose operating systems and interact frequently with email, websites, cloud services and external files, exposing them to commodity malware as well as targeted tools. Malware can provide persistence, steal credentials, enumerate the network, disable security software and download additional payloads; ransomware encrypts or destroys data and may also exfiltrate information before demanding payment.` },
      { p: `Ransomware does not need to reach a PLC to disrupt an industrial organization. If it disables corporate identity services, file servers, communications, billing, logistics or maintenance systems, the organization may be unable to operate safely or confidently, and operators may shut down processes as a precaution while the scope is investigated. This was the central operational consequence of the Colonial Pipeline incident.` },
      { p: `NotPetya provides an even broader example of destructive malware crossing organizational and sector boundaries. It began in June 2017 through a compromised update mechanism associated with the Ukrainian M.E.Doc accounting application. After entering enterprise networks, it propagated using stolen credentials, legitimate administrative tools, and exploitation associated with vulnerable SMB services. Although presented as ransomware, it was primarily destructive because recovery of encrypted systems was generally not possible.` },
      { p: `Industrial companies were among those affected, demonstrating that malware does not need ICS-specific capabilities to cause industrial disruption. Flat enterprise networks, extensive administrative privileges, unpatched Windows systems and unrestricted SMB communication allowed the malware to move quickly; where Level 4 or OT-supporting services shared the same trust relationships, operational consequences became more severe.` },
      { p: `MITRE ATT&CK maps encryption for disruption to Data Encrypted for Impact, T1486, destructive deletion to Data Destruction, T1485, exploitation of internal services to Exploitation of Remote Services, T1210, with the corresponding ICS technique T0866. The principal controls are network segmentation, tested offline backups, endpoint protection, application allowlisting, restricted administrative privileges and rapid isolation of infected systems.` },

      { h: 'USB Devices, Portable Media & Physical Access' },
      { p: `Although Level 5 is highly connected, attacks can also begin through physical access and removable media. Employees and contractors may connect USB storage devices, external disks, mobile phones or diagnostic equipment to corporate systems. A malicious or previously infected device can introduce malware, copy sensitive information or install unauthorized tools.` },
      { p: `MITRE ATT&CK for ICS maps malware propagation through portable media to Replication Through Removable Media, T0847 (Enterprise T1091); the use of laptops and other portable devices moving between networks is represented by Transient Cyber Asset, T0864.` },
      { p: `Portable engineering and maintenance laptops are particularly important because they may connect first to a corporate network and later to Level 4 or lower-level systems. Even with strong network segmentation, the laptop becomes a physical carrier across the boundary, and the same risk applies to USB devices used to transfer updates, configuration files, reports or antivirus signatures into more isolated environments. Physical access to an unattended Level 5 workstation may also allow booting from external media, installing a hardware keylogger, copying locally stored data or using an already authenticated session. Corporate offices, server rooms and network cabinets must be treated as part of the security architecture.` },
      { p: `Controls should include restricting removable media by policy and technical device control, disabling automatic execution, scanning approved media before use, encrypting portable storage and maintaining dedicated media for OT transfers. Contractor and maintenance laptops should be approved, patched and scanned before connection. Where files must cross into the OT environment, they should pass through a controlled transfer station in the DMZ rather than being carried directly from an ordinary corporate workstation to an operational asset.` },

      { h: 'Endpoint Hardening' },
      { h: 'Endpoint Discovery and Exposure Verification' },
      { p: `The internal inventory should be compared with directory records, DHCP leases, endpoint-management systems, vulnerability scans and network observations, with external exposure checked using owned-domain searches and Shodan. For example, an internal inventory may list 400 managed workstations while DHCP and directory data show 437 active devices. The difference may include unmanaged contractor laptops, obsolete systems or VMs created outside the normal process. External search results are not always current and should be confirmed against the organization's own network configuration; they are useful for identifying discrepancies, not as the sole source of truth.` },
      { h: 'Disabling Unnecessary Services' },
      { p: `Services, software and protocols that are not required should be disabled or removed. Common examples include SMBv1, Telnet, unused FTP servers, legacy web-management interfaces, old remote-support agents, unused print services and unnecessary database listeners. For example, a Windows file server may still have SMBv1 enabled because a scanner used it years earlier and has since been replaced. SMBv1 provides no current business value and should be removed. Disabling a service should be preceded by dependency testing, since in industrial organizations a service that appears obsolete may still be used by an old reporting application or Level 4 integration; the correct approach is to confirm the dependency, document the decision, and disable the service in a controlled window.` },
      { h: 'Application Allowlisting' },
      { p: `Application allowlisting permits approved software to execute while blocking or auditing unknown applications and scripts, using AppLocker or Windows Defender Application Control on Windows and file permissions, package controls or mandatory access-control frameworks on Linux. A practical rollout begins in audit mode: monitor execution on administrator workstations for several weeks, identify legitimate software, then enforce rules allowing OS components, signed business applications, approved maintenance tools and authorized scripts. Executables launched from user-writable directories such as Downloads, temp folders and email-attachment locations can then be restricted. Allowlisting is especially suitable for jump hosts and administrative workstations with a stable, limited software set; it is harder on development systems where software changes frequently, requiring exceptions and staged deployment.` },
      { h: 'Secure PowerShell Usage' },
      { p: `PowerShell is essential for Windows administration but is also widely abused for reconnaissance, payload execution and lateral movement. Removing it completely is often impractical. A better approach restricts who can use it, controls which scripts may execute, and collects detailed logs. A concrete baseline: enable PowerShell Script Block Logging, Module Logging and Transcription via Group Policy; forward these to a central collector; restrict remoting to approved management hosts; use signed scripts for recurring administrative functions; and use Constrained Language Mode with application-control policies to limit access to potentially dangerous .NET and COM functionality. Execution policy is not itself a security boundary since it can be bypassed by a sufficiently privileged user or process. It is useful only as one layer combined with application control, privilege restriction and logging. For example, a help-desk technician may run a signed password-reset script but not arbitrary downloaded scripts, and an alert can trigger when PowerShell starts with encoded commands, downloads content, or executes from an unusual user profile directory.` },
      { h: 'USB and Removable-Media Restrictions' },
      { p: `Removable storage should be restricted by role: ordinary users read-only, privileged workstations blocked completely, approved maintenance teams given documented exceptions. A concrete Windows configuration denies execution from removable media for all endpoints and denies write access except for an authorized transfer group, with AutoRun/AutoPlay disabled and approved media encrypted, uniquely identified and scanned before use. The most important industrial example is a laptop or USB drive moving between Level 5 and an engineering or OT environment. Even with strong network segmentation, the device can carry malware across the boundary, so corporate USB devices should never connect directly to an HMI, engineering workstation or historian; required files should pass through a dedicated transfer station or scanning workflow at a controlled boundary.` },

      { h: 'Capital Investment: EDR / XDR Platforms' },
      { p: `Endpoint Detection and Response platforms continuously collect endpoint telemetry, detect suspicious behaviour, and support containment actions such as isolating a workstation or terminating a malicious process; Extended Detection and Response combines endpoint data with identity, email, cloud and network information. Compared with traditional antivirus, EDR provides better visibility into attack chains. For example, it can correlate a malicious attachment, PowerShell execution, credential dumping and lateral movement, then isolate the endpoint before the attacker reaches Level 4. ROI comes from faster detection and response, reduced investigation time, and the ability to contain ransomware before widespread encryption. Costs include licensing, agent deployment, tuning, continuous alert review and compatibility testing with older applications. At Level 5, EDR is generally less operationally risky than deployment directly on real-time OT endpoints, but critical business and Level 4-supporting applications should still be tested before enabling aggressive automated response.` },

      { h: 'Capital Investment: Security-Awareness Training' },
      { p: `Configuration and technical controls cannot prevent every social-engineering attempt. Commercial awareness platforms provide structured training, simulated phishing campaigns, completion tracking and targeted follow-up. A useful programme goes beyond generic annual videos, for example training finance employees on fraudulent payment requests, IT administrators on fake password-expiration notices, and engineers on malicious vendor documentation, with simulated phishing results identifying departments needing more support. ROI is difficult to measure directly, but indicators include reduced interaction with simulated phishing, faster user reporting and fewer compromised accounts. Training should never be used to shame employees. A punitive approach discourages reporting, while rapid reporting lets the security team remove a malicious message before other users open it.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Reconcile the endpoint inventory against DHCP, directory and management data',
        'Disable SMBv1, Telnet and other legacy services after dependency testing',
        'Deploy application allowlisting (WDAC or AppLocker) in audit mode, then enforce',
        'Enable PowerShell Script Block, Module and Transcription logging',
        'Restrict PowerShell remoting to approved management hosts',
        'Block execution from removable media; disable AutoRun and AutoPlay',
        'Limit USB write access to an authorized transfer group',
        'Route OT-bound files through a scanned transfer station, never direct USB',
        'Test EDR policies before enabling automated containment',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Windows Defender Application Control (WDAC)', url: search('Windows Defender Application Control') },
        { label: 'PowerShell Script Block Logging Group Policy', url: search('PowerShell Script Block Logging Group Policy') },
        { label: 'PowerShell Constrained Language Mode', url: search('PowerShell Constrained Language Mode') },
        { label: 'Removable storage access control Group Policy', url: search('removable storage access control Group Policy') },
        { label: 'Disable Office macros via Group Policy', url: search('disable Office macros Group Policy') },
        { label: 'SwiftOnSecurity Sysmon config (starter template)', url: search('SwiftOnSecurity Sysmon config GitHub') },
        { label: 'EDR vs XDR platform comparison', url: search('EDR XDR comparison') },
        { label: 'Security-awareness training platforms', url: search('security awareness training platform') },
      ] },
    ],
  },

  files: {
    blocks: [
      { h: 'Lateral Movement Toward Level 4' },
      { p: `After establishing access at Level 5, attackers search for routes toward Level 4. Common targets include enterprise resource planning systems, maintenance-management platforms, production databases, centralized authentication services, backup servers and shared file repositories: systems that may contain network diagrams, equipment inventories, vendor documentation, configuration files and credentials revealing how the industrial environment is organized.` },
      { p: `Lateral movement normally uses legitimate enterprise protocols and administration tools: RDP, SMB, Windows Management Instrumentation, PowerShell, SSH and commercial remote-support software. MITRE ATT&CK maps these to Remote Services (T1021), Lateral Tool Transfer (T1570) and Valid Accounts (T1078); the corresponding ICS techniques are Remote Services (T0886), Lateral Tool Transfer (T0867) and Valid Accounts (T0859).` },
      { p: `The critical architectural question is whether Level 5 systems are permitted to communicate directly with Level 4 or OT assets. If broad firewall rules, shared Active Directory domains, dual-homed servers or unmanaged administrative connections exist, the attacker can use them as legitimate pathways. A historian replicated to the enterprise, a patch-management server with access to both zones, or a remote-support host connected to several levels may become the bridge. File servers and shared repositories are named explicitly in the threat literature as one of the most common such bridges, which is why their exposure and backup posture matter as much as their content.` },

      { h: 'Backup and Recovery' },
      { p: `Ransomware is the threat most likely to halt an industrial organization through Level 5 alone, as Colonial Pipeline and NotPetya demonstrated. A tested backup and recovery capability is therefore one of the highest-value measures available, and much of it can be achieved through configuration of existing systems.` },
      { p: `Backups should follow the principle of keeping multiple copies on more than one medium, with at least one copy held offline or in immutable storage that cannot be modified or deleted by an account compromised on the network. This is essential because modern ransomware deliberately searches for and encrypts reachable backup shares before triggering encryption of production data. A backup that is permanently mounted and writable from a compromised server offers little protection.` },
      { p: `Identity services such as Active Directory, configuration data, email and critical file shares should be prioritized. Restoration should be tested on a defined schedule rather than assumed to work, because an untested backup frequently fails when it is most needed. Backup administration should use separate privileged accounts, consistent with the least-privilege approach on the Authentication node, so that a single compromised domain administrator cannot reach both production systems and their backups.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Keep at least one backup copy offline or immutable',
        'Use separate credentials for backup administration',
        'Test restoration of identity services, email and critical file shares on a schedule',
        'Restrict file-server paths that bridge Level 5 toward Level 4',
        'Log and review large or unusual file transfers',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'The 3-2-1 backup rule and immutable backups against ransomware', url: search('3-2-1 backup rule immutable backup ransomware') },
      ] },
    ],
  },

  databases: {
    blocks: [
      { h: 'Network Hardening' },
      { p: `Configuration of existing host firewalls, routers, switches, VPN appliances and access-control lists can significantly reduce lateral movement without purchasing new infrastructure.` },
      { h: 'Host Firewalls' },
      { p: `Host-based firewalls should be enabled on servers and workstations with centrally managed rules, defaulting to block unsolicited inbound connections and allow only documented services from approved source networks. An employee workstation normally needs to initiate web, email and business-application connections but rarely needs to accept inbound SMB, RDP or PowerShell remoting from every other workstation. Blocking these inbound services reduces malware's ability to move laterally. A backup server may accept traffic only from registered backup agents and an administration subnet rather than the entire corporate network. Firewall logging should be enabled for blocked connections and important allowed connections, with logs forwarded to the monitoring architecture below.` },
      { h: 'Restriction of RDP' },
      { p: `Remote Desktop Protocol should never be directly exposed to the public internet. Internally, it should be allowed only where operationally necessary and restricted to approved administrators and management sources. A concrete configuration blocks TCP port 3389 at the internet firewall, requires connection through an MFA-protected VPN, and then permits RDP only from a bastion host to a limited set of servers, with Network Level Authentication enabled, shared accounts prohibited, and idle sessions disconnected automatically. On ordinary workstations, inbound RDP can be disabled completely; where support personnel need remote assistance, access should go through an approved support mechanism with user awareness and logging.` },
      { h: 'Network Segmentation' },
      { p: `Even at Level 5, a single flat corporate network is inappropriate. Employee devices, servers, identity infrastructure, backup systems, administration hosts, guest networks and Level 4-facing services should be separated into security zones. For example, separate VLANs for ordinary workstations, corporate servers, privileged administration workstations, backup infrastructure, guest wireless access and externally published services, with firewall rules allowing only flows required by documented business processes. Segmentation between Level 5 and Level 4 should be especially strict: data required by corporate users should pass through approved services and the industrial DMZ rather than broad routing rules, and a Level 5 workstation should never connect directly to an HMI, engineering workstation, PLC or site historian.` },
      { h: 'Removal of Unused Ports and Rules' },
      { p: `Firewall policies often accumulate temporary rules that become permanent. A vendor may request access for one week, a migration project may open a database port, or testing may expose a web application that is never removed. A quarterly rule review should identify entries with no active owner, no documented purpose, or no observed traffic. For example, a rule allowing all Level 5 systems to reach a Level 4 server on "any port" should be replaced with rules permitting only the specific source, destination and application protocol required. Unused switch ports should be disabled or placed in an isolated VLAN to reduce unauthorized physical connections.` },

      { h: 'Monitoring and Detection Infrastructure' },
      { p: `Preventive hardening cannot guarantee that every phishing email, stolen password or malicious program will be blocked. Level 5 therefore requires monitoring capable of identifying suspicious behaviour after an attacker gains an initial foothold. Many organizations can improve this using features built into Windows and freely available security tools rather than immediately purchasing a commercial SIEM. The objective is not to collect every possible event: excessive logging without analysis creates storage costs and hides important activity in noise. The organization should collect events supporting the attack paths identified across this level, including suspicious authentication, privilege escalation, PowerShell abuse, malware execution, remote access and lateral movement toward Level 4, combining endpoint logs, identity events and network observations rather than depending on one detection method.` },
      { h: 'Windows Event Forwarding' },
      { p: `A built-in Windows capability that can send selected events from workstations and servers to one or more Windows Event Collector systems, deployable via Group Policy without a commercial endpoint agent. A practical deployment collects:` },
      { list: [
        'Successful and failed logins',
        'Account creation, deletion and group-membership changes',
        'Use of privileged accounts',
        'New scheduled tasks and services',
        'PowerShell operational logs',
        'Windows Firewall events',
        'Remote desktop logins',
        'Antivirus detections',
        'Changes to audit policy',
      ] },
      { p: `For example, a detection rule can identify ten failed VPN or Windows logins followed by a successful login from the same source, or alert when a normal employee account is added to Domain Admins or a dormant account authenticates after months of inactivity. Rather than forwarding all events, define subscriptions for high-value security events, prioritizing domain controllers, VPN gateways, jump hosts, email servers and systems with access toward Level 4.` },
      { h: 'Sysmon' },
      { p: `A free Microsoft Sysinternals service that records detailed endpoint activity in the Windows event log: process creation, network connections, driver loading, file creation, registry changes, DNS queries and more, depending on configuration. It is valuable because the standard Windows log may record that a user logged in without detail on what ran afterward. Sysmon can record that powershell.exe was launched by a Microsoft Word process, used an encoded command, and opened a connection to an external address: a sequence far more suspicious than PowerShell execution alone. Configuration must be tuned to high-risk parent-child process combinations, execution from temporary directories, script interpreters, credential-access tools, unusual network connections and changes to security controls, since recording every possible event on every workstation generates excessive data. Sysmon does not block malicious activity. Its role is to create telemetry forwarded through Windows Event Forwarding or another collection platform.` },
      { h: 'Wazuh' },
      { p: `An open-source security platform combining endpoint agents, log collection, file-integrity monitoring, vulnerability detection and rule-based alerting, plus a built-in SIEM component, active-response automation and cloud workload protection. It can receive Windows events and Sysmon telemetry and provide a centralized interface for searches and alerts. A small organization can deploy it first on high-value Level 5 systems: domain controllers, VPN servers, administrative workstations, jump hosts. Example detection scenarios:` },
      { list: [
        'A new local administrator account is created',
        'An executable is launched from an email-attachment directory',
        'A privileged account logs in from an unusual endpoint',
        'Security logging is stopped or cleared',
        'A system file or critical configuration changes',
        'PowerShell downloads content from an external address',
        'A user workstation begins scanning multiple internal systems',
      ] },
      { p: `Wazuh reduces licensing cost but is not operationally free. The organization still needs server capacity, rule tuning, storage, maintenance and personnel able to investigate alerts. An untuned deployment may produce so many false positives that important activity is ignored.` },
      { h: 'Zeek' },
      { p: `An open-source network security monitoring platform that converts observed traffic into detailed protocol and connection logs, focusing strongly on network metadata and behaviour rather than signatures alone. At Level 5, Zeek can record DNS requests, web connections, TLS sessions, file-transfer metadata and communication between network zones. A useful placement is at the boundary between internet-facing services and the internal network, or between Level 5 and the industrial DMZ. For example, Zeek can reveal a workstation that normally talks only to corporate services suddenly making DNS requests for algorithmically generated domains and opening encrypted connections to an unusual external host, or a Level 5 workstation attempting to contact multiple Level 4 addresses over SMB or RDP, indicating reconnaissance or lateral movement. Because much enterprise traffic is encrypted, Zeek may not see message content, but connection metadata, certificates, DNS patterns and traffic timing still support detection.` },
      { h: 'Suricata' },
      { p: `An open-source intrusion-detection and intrusion-prevention engine analyzing network traffic using signatures and protocol parsers, suitable for known exploit attempts, malware communication, scanning behaviour and policy violations. Deployed on a network sensor monitoring internet ingress/egress, community or internally developed rules can alert on known ransomware infrastructure, exploitation of vulnerable web applications, suspicious SMB activity and unexpected remote administration protocols. At the Level 5-to-Level 4 boundary, Suricata can also enforce architectural expectations. If only HTTPS from one reporting server is permitted, an alert can fire when RDP, SMB or PowerShell remoting is observed across that boundary. Suricata and Zeek are complementary: Suricata provides strong signature-based detection, Zeek provides rich behavioural and protocol metadata. This reflects a hybrid IDS approach where known threats are detected with signatures and abnormal communication is detected through behavioural context.` },
      { h: 'Cloud Identity and Email Logs' },
      { p: `Where the organization uses a cloud identity provider or cloud email, the monitoring architecture should also collect the audit and sign-in logs these platforms generate: interactive and non-interactive sign-ins, MFA failures and prompts, conditional-access results, changes to privileged roles, and OAuth application-consent grants, which attackers increasingly abuse to obtain persistent access without a password. These logs are available without additional licensing in most platforms and ensure an identity compromise is visible whether it occurs against Active Directory or the cloud tenant.` },
      { h: 'Centralized Log Collection' },
      { p: `The individual tools are useful only when their data is brought together. Logs should be centralized so events from several systems can be correlated and retained even if an attacker deletes local records. For example, a complete attack sequence may consist of:` },
      { list: [
        'The email gateway delivers a malicious attachment',
        'Sysmon records Word launching PowerShell',
        'Windows logs record a new scheduled task',
        'The DNS sensor records communication with an unusual domain',
        'The VPN server records a later login using the victim’s account',
        'The firewall records connection attempts toward Level 4',
      ], plain: true },
      { p: `No single log proves the complete intrusion. Centralized collection lets these events be connected by time, user, host and network address. Retention periods should reflect operational and regulatory requirements, with high-value authentication and administrative logs retained longer than routine workstation events, and system clocks synchronized so timestamps support correlation and incident reconstruction. Monitoring should begin with a limited set of high-confidence use cases:` },
      { list: [
        'Privileged group-membership changes',
        'Successful logins after repeated failures',
        'New or reactivated dormant accounts',
        'VPN logins from unusual countries or devices',
        'PowerShell launched by Office applications',
        'Execution from temporary or user-download directories',
        'Disabling of antivirus, logging or firewall services',
        'Unexpected RDP or SMB activity',
        'Network scanning',
        'Direct Level 5 communication with unauthorized Level 4 systems',
      ] },
      { p: `This architecture ties directly into broader intrusion-detection practice: Windows Event Forwarding, Sysmon and Wazuh provide host and identity telemetry, Suricata provides signature-based network detection, and Zeek supports behavioural and anomaly-oriented analysis. Together they form a low-cost hybrid monitoring capability that is more resilient than any single detection technology.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Enable host firewalls; block unsolicited inbound connections by default',
        'Block RDP at the internet edge; allow internal RDP only from bastion sources',
        'Enable Network Level Authentication and disconnect idle sessions',
        'Scope VPN access by role instead of granting full network reach',
        'Segment workstations, servers, identity, backup and guest networks into zones',
        'Review firewall rules quarterly; remove stale rules and unused ports',
        'Synchronize clocks and centralize logs with defined retention',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Windows Defender Firewall Group Policy', url: search('Windows Defender Firewall Group Policy') },
        { label: 'Restrict RDP via Windows Group Policy', url: search('restrict RDP Windows Group Policy') },
        { label: 'Windows Event Forwarding setup', url: search('Windows Event Forwarding setup') },
        { label: 'Sysmon, official Microsoft Sysinternals download', url: 'https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon' },
        { label: 'Wazuh, open-source SIEM/XDR', url: 'https://wazuh.com' },
        { label: 'Zeek, network security monitoring', url: 'https://zeek.org' },
        { label: 'Suricata, signature-based IDS/IPS', url: 'https://suricata.io' },
        { label: 'Entra ID sign-in logs / Google Workspace audit logs', url: search('Entra ID sign-in logs Google Workspace audit logs') },
      ] },
    ],
  },
};
