// Level 0 (Field Devices: sensors, actuators) hardening guide content, keyed
// by diagram node id. 'l0' is the level-wide overview shown when the band
// label is clicked; the rest are per-component deep dives shown when a
// specific asset box is clicked. Mirrors the structure of the levels above:
// primary field-device types (Sensors & Transmitters, Actuators & Drives,
// Wireless Field Devices, Fieldbus Gateways) sit alongside the shared
// infrastructure tier that supports them (Physical Security,
// Field Maintenance, Signal Monitoring, Device Lifecycle).
//
// Block shapes: { h } sub-heading, { p } paragraph, { list } bullet list,
// { links } a labeled list of external resources (real URLs where
// available, otherwise a search link built from the exact recommended
// search term).

const search = (q) => `https://www.google.com/search?q=${encodeURIComponent(q)}`;

export const LEVEL0_CONTENT = {
  l0: {
    blocks: [
      { h: 'Field Devices and the Physical Process' },
      { p: `Level 0 contains the devices that directly measure or influence the physical process: sensors, transmitters, analyzers, limit switches, valve positioners, actuators, motor starters, variable-frequency drives, breakers and other field instrumentation. These devices provide process information to controllers at Level 1 and carry out the physical commands generated by the control system.` },
      { p: `Level 0 is where a cyber incident becomes a physical event. A false sensor value may cause a controller to act incorrectly, and unauthorized operation of a valve, motor or breaker may directly affect production, equipment or personnel safety. Security at this level must protect the integrity of measurements and commands while ensuring that devices fail safely when communication, power or control is lost.` },
      { p: `Many Level 0 devices have limited authentication, logging and processing capability. Some use simple analog signals, others communicate through fieldbus, Ethernet or wireless protocols, and endpoint security software usually cannot be installed on them. Their protection therefore depends on secure configuration, restricted communication, physical protection, signal validation, controlled maintenance and tested recovery.` },

      { h: 'Role of Level 0 in the Purdue Model' },
      { p: `Level 0 represents the physical process and the instruments that interact with it. Level 1 controllers execute control logic but depend on Level 0 devices for both measurements and physical action.` },
      { p: `Sensors and transmitters report conditions such as temperature, pressure, flow, level, speed, vibration, position, voltage and current, as an analog signal (such as 4-20 mA) or through digital protocols such as HART, Modbus, DNP3, IEC 61850 or a vendor-specific fieldbus. Analyzers measure more complex characteristics used for process adjustment, environmental compliance or safety decisions. Actuators such as valves, motors, pumps, breakers and positioners turn controller outputs into physical action, and some contain intelligent positioners or embedded controllers. Variable-frequency drives, protection relays and IEDs add further configuration and communication functions close to the process.` },
      { p: `Even simple devices with no network connection remain security-relevant, because their wiring, calibration, range and physical condition determine whether the controller receives accurate information and whether commands are executed correctly. Level 0 devices should communicate only with their assigned Level 1 controller, local field gateway or approved maintenance system, never directly with enterprise networks, cloud platforms or the internet.` },

      { h: 'Threat Landscape Summary' },
      { p: `The main Level 0 threats are manipulation of sensor values, unauthorized operation of actuators, physical tampering, modification of calibration or configuration, abuse of fieldbus and wireless communication, signal interruption and firmware compromise. The techniques below are mapped to MITRE ATT&CK for ICS, as at the previous levels.` },
      { p: `A representative attack path is: compromise of an engineering or maintenance system → access to a Level 1 controller or field gateway → connection to a smart sensor or actuator → modification of calibration, configuration, limits or commands → incorrect physical behaviour. An attacker with physical access has a shorter path: access to a cabinet or device → connection through a local port or replacement of wiring → manipulation of the signal → physical impact.` },
      { p: `See the Sensors & Transmitters, Actuators & Drives, Wireless Field Devices, Fieldbus Gateways, Physical Security, Field Maintenance, Signal Monitoring and Device Lifecycle nodes on this level for the specific techniques and controls addressing each part of this chain.` },

      { h: 'Implementation Priorities' },
      { list: [
        'Identify all field devices, their locations, firmware, calibration, connected controllers and process consequences',
        'Create a secure commissioning baseline for each important device (range, scaling, communication, fail state, approved configuration)',
        'Remove default credentials, disable unused interfaces and prevent direct connectivity from enterprise or public networks',
        'Restrict each device to its approved controller, gateway and maintenance systems',
        'Secure cabinets, wiring, local ports, mode switches, wireless commissioning and maintenance equipment, and protect against environmental damage',
        'Define explicit responses for missing, stale, frozen or implausible signals, loss of actuator communication, and loss or spoofing of GNSS timing',
        'Add signal-plausibility checks, independent feedback, periodic calibration and comparison between related measurements',
        'Protect safety-related instrumentation through stronger separation, authorization, change control and physical security',
        'Establish passive monitoring, configuration comparison and alerts for unexpected masters, maintenance activity, parameter changes and signal-quality problems',
        'Replace unsupported devices and invest in secure field gateways, signed firmware, tamper and environmental monitoring, redundant sensing, independent actuator feedback and test equipment',
      ] },
      { p: `Level 0 is the source of process measurements and the point at which commands become physical actions. Its security depends on protecting the whole signal path, not only the network connection. Accurate inventory, secure commissioning, controlled maintenance, physical and environmental protection, communication restriction, signal validation and verified recovery provide the most practical defence against manipulation of field devices and the physical process.` },

      { h: 'Resources' },
      { links: [
        { label: 'NIST SP 800-82 Rev. 3, OT security control baseline', url: 'https://csrc.nist.gov/pubs/sp/800/82/r3/final' },
        { label: 'MITRE ATT&CK for ICS matrix', url: 'https://attack.mitre.org/matrices/ics/' },
        { label: 'CISA Industrial Control Systems advisories', url: 'https://www.cisa.gov/news-events/cybersecurity-advisories?f%5B0%5D=advisory_type%3A93' },
      ] },
    ],
  },

  sensor: {
    blocks: [
      { h: 'Sensor Manipulation and False Data' },
      { p: `A controller assumes its sensor values are accurate. Changing a value, its calibration or its scaling can make the controller act incorrectly while appearing normal in software (Spoof Reporting Message, T0856; Manipulate I/O Image, T0835; Modify Parameter, T0836).` },
      { p: `Attacks include changing range or units, modifying calibration, replacing the signal with a fixed value, slowly shifting the value, replaying old measurements, impersonating a disconnected sensor, or altering quality and alarm limits. Gradual manipulation is harder to detect than an extreme value, because a plausible but false reading can stay within alarm limits while pushing the process toward an unsafe state.` },
      { p: `Research on hidden false-data injection shows an attacker may disable the real sensor and supply realistic fake readings, so detection must also consider signal freshness, device identity and consistency with related measurements.` },

      { h: 'Sensor Configuration and Calibration' },
      { p: `Limit sensor settings to process requirements: range, units, scaling, damping, calibration coefficients, alarm limits, update rate, diagnostics, identification and fail response. Avoid unnecessarily broad ranges, which hide manipulation and reduce accuracy, and disable remote configuration where it is not needed.` },
      { p: `Calibrate and verify devices against a traceable reference on a defined schedule: regular calibration maintains accuracy and also exposes slow drift or manipulation that stays within alarm limits.` },
      { p: `Calibration changes should be authorized and checked against the baseline, and the device identity reported over the network checked against the asset record.` },

      { h: 'Analog Signals and Wiring' },
      { p: `Document and label field wiring, lock junction and marshalling boxes, and ensure spare pairs and unused terminals give no undocumented route into the system. Follow engineering requirements for shielding, grounding and cable separation, and use signal isolators where needed.` },
      { p: `Configure the controller to treat out-of-range conditions as faults rather than valid readings, and use line-fault detection so open circuits, shorts, power loss and stale values produce clear diagnostics.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Limit sensor configuration to actual process requirements',
        'Avoid unnecessarily broad ranges; disable unneeded remote configuration',
        'Calibrate against traceable references on a defined schedule',
        'Authorize calibration changes and verify them against the baseline',
        'Check the device identity reported over the network against the asset record',
        'Label and lock field wiring, junction and marshalling boxes',
        'Treat out-of-range values as faults and enable line-fault detection',
      ] },
    ],
  },

  actuator: {
    blocks: [
      { h: 'Actuator Manipulation' },
      { p: `An attacker who reaches an actuator or its control path can change the process directly (Unauthorized Command Message, T0855; Brute Force I/O, T0806; Manipulation of Control, T0831), meaning operating valves, motors and breakers, changing speed, stroke limits or direction, switching to local mode, altering protection parameters or disabling feedback.` },
      { p: `A device may obey valid commands while a modified local parameter makes it behave differently, so feedback should confirm the actuator reached the commanded state.` },

      { h: 'Actuator and Drive Hardening' },
      { p: `Configure actuators, positioners and drives so abnormal commands cannot easily cause unsafe movement: operating range, position limits, speed and torque limits, direction, control modes, restart behaviour, interlocks, protection parameters, command timeout, feedback and fail-safe position.` },
      { p: `Restrict local/manual control, enable automatic restart only where the resulting movement is safe, and use command feedback to confirm the requested physical result.` },

      { h: 'Fail-Safe Behaviour' },
      { p: `Define each important signal's and actuator's response to failure. For sensors, decide what happens when a value is missing, out of range, frozen, stale, poor-quality or inconsistent with related measurements; a stale-value timer or quality flag should alarm and, where required, move the process to a safe mode rather than trusting the last value indefinitely.` },
      { p: `For actuators, document the required state after loss of power, communication or signal (fail open, fail closed or hold), based on process and safety analysis.` },

      { h: 'Capital Investment: Independent Actuator Feedback' },
      { p: `Independent actuator feedback, separate position switches, motor current, independent speed, breaker auxiliary contacts, flow or pressure confirmation makes it harder for a compromised actuator to falsely report success.` },

      { h: 'Capital Investment: Redundant and Diverse Sensing' },
      { p: `Redundant and diverse sensing keeps a single failed or compromised device from misleading the controller. For high-consequence measurements, diversity (different technologies, vendors or paths) is stronger than identical duplication, evaluated by voting or comparison with alarms on disagreement.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Configure position, speed, torque and direction limits on actuators and drives',
        'Restrict local and manual control modes',
        'Allow automatic restart only where the resulting movement is safe',
        'Confirm every commanded state through feedback',
        'Define fail states (open, closed or hold) from process and safety analysis',
        'Alarm on stale or missing signals with defined fallback behaviour',
        'Add independent feedback for high-consequence actuators',
        'Use diverse redundant sensing for critical measurements',
      ] },
    ],
  },

  wireless: {
    blocks: [
      { h: 'Wireless Attacks' },
      { p: `Wireless devices may use WirelessHART, ISA100.11a, Wi-Fi, Bluetooth, Zigbee, LoRaWAN, cellular or vendor radio. Gaining access maps to Wireless Compromise (T0860) and interception to Wireless Sniffing (T0887). Risks include unauthorized association, key theft or reuse, replay, rogue gateways, jamming, eavesdropping and physical device replacement.` },
      { p: `As with the wired protocols at Levels 1 and 2, key management is central: enable the strongest authentication and encryption, do not reuse default network keys, do not leave Zigbee or LoRaWAN devices on vendor-default keys, and keep joining modes off except during commissioning. Treat wireless gateways as security boundaries, since one compromised gateway can expose many devices.` },

      { h: 'GNSS and Timing Attacks' },
      { p: `Some devices depend on satellite time (commonly GPS) for time-tagging, sequence-of-events records and, in electrical systems, synchrophasor and protection functions. An attacker can spoof GNSS to inject false time or position, or jam it to remove timing. Devices should use a trusted, hardened time source, hold accurate time during short outages.` },

      { h: 'Wireless Hardening' },
      { p: `Use the strongest supported security mode with unique network and device keys, removal of vendor defaults, restricted joining periods, device allowlists, protected gateway administration, secure key storage, key replacement after suspected compromise, monitoring for unknown devices, appropriate radio coverage and procedures for jamming or loss.` },
      { p: `Place gateways in a protected zone, keep their management interfaces off general networks, and disable unused Bluetooth, Wi-Fi and NFC functions.` },

      { h: 'Capital Investment: Secure Wireless and Timing Infrastructure' },
      { p: `Secure wireless and timing infrastructure may use managed gateways, central key management, directional antennas, radio monitoring and redundancy, plus alternative paths or local fail-safe for jamming or gateway loss. Where devices use satellite time, hardened or anti-spoofing GNSS receivers, holdover oscillators and an independent internal time source reduce the impact of spoofing or jamming.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Enable the strongest supported wireless security modes',
        'Replace vendor-default network and device keys',
        'Close joining and commissioning modes outside authorized work',
        'Allowlist devices and monitor for unknown associations',
        'Keep gateway administration off general networks',
        'Replace keys after any suspected compromise',
        'Define procedures for jamming and gateway loss',
        'Use hardened GNSS receivers and holdover for timing-critical devices',
      ] },
    ],
  },

  fieldbus: {
    blocks: [
      { h: 'Fieldbus and Protocol Abuse' },
      { p: `Many field protocols provide little authentication, encryption or command integrity. An unauthorized system on the field network may read measurements, write configuration, change addresses, issue commands or run diagnostics, or impersonate the controller (Rogue Master, T0848).` },
      { p: `Communication should be restricted by both device identity and function: a controller may need read/write access, a historian read-only, and engineering or calibration functions only from approved maintenance systems.` },

      { h: 'Signal Interruption and Denial of Service' },
      { p: `An attacker can affect the process by interrupting a measurement or command without changing its content (Denial of Service, T0814; Block Reporting Message, T0804; Loss of View, T0829).` },
      { p: `Even encrypted traffic is vulnerable to jamming and selective packet loss; research shows important encrypted ICS packets can be identified by timing and size and selectively dropped. Loss of a signal should have a defined response, and the controller should not run indefinitely on an old value unless that has been assessed as safe.` },

      { h: 'Restrict Communication' },
      { p: `A device should communicate only with the systems it needs. Separate field networks by control cell, restrict communication to approved device pairs through switches, access lists, firewalls or gateways, and distinguish process traffic from engineering traffic where possible.` },
      { p: `Prohibit direct communication from Level 2, Level 3, enterprise IT or the internet; route engineering access through an approved Level 2 workstation or gateway. Remote sites should use private addressing, managed gateways or VPNs, never a directly internet-reachable instrument.` },

      { h: 'Capital Investment: Secure Field Gateways' },
      { p: `Secure field gateways can authenticate, encrypt, allowlist devices, convert protocols, filter function codes, log activity and separate monitoring from configuration traffic, protecting legacy devices that cannot protect themselves, but the gateway becomes a critical asset to harden, monitor and back up.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Separate field networks by control cell',
        'Restrict communication to approved device pairs via switches, ACLs or gateways',
        'Separate process traffic from engineering and calibration traffic',
        'Prohibit direct communication from Level 2, Level 3, enterprise IT or the internet',
        'Route engineering access through an approved Level 2 system',
        'Define responses to lost signals; never trust stale values indefinitely',
        'Harden, monitor and back up field gateways as critical assets',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'Secure field/protocol gateways', url: search('secure field protocol gateway ICS') },
      ] },
    ],
  },

  physical: {
    blocks: [
      { h: 'Physical Tampering' },
      { p: `Field devices often sit outside control rooms in production areas, substations, pipelines and outdoor cabinets, where an attacker may short or replace a sensor, inject a signal, move a selector, connect a tool, remove a memory card or alter wiring (leading to Damage to Property, T0879). Network controls cannot prevent this, so cabinets, junction boxes and devices must be part of the physical security programme.` },

      { h: 'Physical and Environmental Protection' },
      { p: `Install devices in locked enclosures or controlled areas with cabinet locks, controlled keys, tamper-evident seals, tamper switches, access alarms, port covers, protected cable routes, secured antennas and periodic inspection. Do not leave mode or cabinet keys in the equipment, do not print passwords on labels, and clear or securely store removed devices and memory cards.` },
      { p: `Control and monitor environmental conditions as well, because temperature, humidity, water, dust, vibration and fire can disable a device or cause false readings, and a sudden change can indicate tampering: provide appropriate ingress protection and monitor critical or remote cabinets for temperature, humidity, water and smoke, with alerts integrated into existing monitoring.` },

      { h: 'Safety-System Interaction' },
      { p: `Sensors and actuators used by a Safety Instrumented System need stronger protection than ordinary instrumentation, since their compromise maps to Loss of Safety (T0880).` },
      { p: `Keep safety instrumentation independent from the Basic Process Control System to the extent required by the safety design, assess shared sensors, networks and tools for common-failure paths, restrict safety-device configuration to authorized personnel with additional approval and validation against the Safety Requirements Specification, and introduce any controls in cooperation with functional-safety engineers so they never block the safety function.` },

      { h: 'Capital Investment: Hardened Enclosures and Tamper Monitoring' },
      { p: `Hardened enclosures and tamper/environmental monitoring, reinforced enclosures, electronic access control, tamper switches, cabinet-open alarms, surveillance and monitoring of temperature, humidity, water and fire, protect high-consequence or remote installations, with alarms integrated into existing monitoring.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Lock enclosures, control keys, and fit tamper seals or switches',
        'Protect cable routes and antennas; cover unused ports',
        'Never print credentials or addressing details on labels',
        'Monitor critical cabinets for temperature, humidity, water and smoke',
        'Integrate tamper and environmental alarms into existing monitoring',
        'Protect safety instrumentation more strictly and validate changes against the SRS',
        'Coordinate safety-instrumentation controls with functional-safety engineers',
      ] },
    ],
  },

  fieldmaint: {
    blocks: [
      { h: 'Calibration and Maintenance Abuse' },
      { p: `Calibration legitimately changes the relationship between the physical quantity and the reported value, so unauthorized calibration produces the same effect as manipulation (Modify Parameter, T0836). Handheld configurators store device data and credentials and can modify many devices, so maintenance must be authorized, recorded and verified before a device returns to service.` },

      { h: 'Secure Commissioning Baseline' },
      { p: `Before a device enters service, record a known-good baseline: model, serial, approved firmware, address, range and scaling, units, alarm and diagnostic settings, fail-safe state, communication parameters, allowed master, accounts, enabled/disabled interfaces, calibration results and installation photos.` },
      { p: `Change default passwords and network keys and disable unused services during commissioning, and store the approved configuration in a protected repository.` },

      { h: 'Secure Maintenance' },
      { p: `Treat maintenance laptops, handheld configurators and vendor tools as transient cyber assets (T0864), and removable media as a replication path (T0847). Connect only approved equipment, using approved software and controlled file transfer, and apply least privilege so a technician calibrating one transmitter cannot reach every device.` },
      { p: `Route remote maintenance through the approved remote-access architecture and a controlled Level 2 system; never allow direct internet access to a device or gateway.` },
      { p: `Record each activity: person, time, location, device, reason, before/after configuration, calibration results and approval to return to service. Remove temporary cables, wireless modes, vendor accounts and bypasses afterward.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Record a commissioning baseline (configuration, calibration, photos) before service',
        'Change defaults and disable unused services during commissioning',
        'Store approved configurations in a protected repository',
        'Approve maintenance tools and treat configurators as transient assets',
        'Apply least privilege to maintenance access',
        'Record each maintenance activity with before-and-after configuration',
        'Remove temporary cables, modes, accounts and bypasses after the work',
      ] },
    ],
  },

  sigmon: {
    blocks: [
      { h: 'Passive Network Monitoring' },
      { p: `Because most Level 0 devices cannot run security agents, monitoring should focus on communication, signal quality, physical consistency and configuration integrity.` },
      { p: `Place passive sensors at field gateways, switches, serial-to-IP converters and wireless gateways, and baseline which controller talks to each device, which maintenance system may configure it, the protocol, polling intervals, normal writes, signal ranges, traffic volume and maintenance windows.` },
      { p: `Alert when an unknown system communicates with a device, a monitoring system issues writes, or configuration traffic occurs outside a maintenance window. Prefer passive monitoring to active scanning, which can disrupt older devices.` },

      { h: 'Signal Plausibility' },
      { p: `Compare measurements with related physical conditions: valve command against position, pump state against flow and pressure, motor command against current and speed, level against inlet and outlet flow, heater output against temperature change, breaker state against voltage and current, and redundant sensors against each other.` },
      { p: `These checks usually fit within existing PLC, SCADA, historian or alarm functions and need not be complex; their purpose is to flag physically impossible or unlikely combinations.` },

      { h: 'Frozen, Stale and Missing Values' },
      { p: `A value unchanged for an unusually long time may be frozen or replayed rather than stable. Track time since last update, quality flags, sequence counters, rate of change, out-of-range conditions and communication heartbeat; stale or invalid measurements should alarm, with defined fallback behaviour for critical functions.` },

      { h: 'Configuration Integrity' },
      { p: `Periodically compare approved configurations with running ones using vendor tools, exported parameters, checksums, configuration-management software or commissioning checklists, prioritizing critical sensors, drives, relays, analyzers and safety devices. Investigate differences rather than restoring automatically.` },

      { h: 'Physical Inspection' },
      { p: `Use operator and maintenance rounds to look for broken seals, unlocked cabinets, unexpected cables, altered switches, connected tools, damaged antennas, changed labels, disturbed wiring and unusual display messages, recording results especially at remote or high-consequence sites.` },

      { h: 'High-Value Alerts' },
      { p: `Useful Level 0 alerts include:` },
      { list: [
        'A new master communicating with a device (Rogue Master, T0848)',
        'Configuration outside a maintenance window',
        'A change of range, units or address',
        'A change of actuator limits or direction',
        'Activation of local/manual mode',
        'Use of a default or dormant account',
        'A disabled interface becoming active',
        'Repeated failed authentication',
        'Loss of signal or a stale measurement (Block Reporting Message, T0804)',
        'A valve command not matching its position',
        'A running motor with no expected current or flow',
        'Large disagreement between redundant sensors',
        'An unexpected wireless association (Wireless Compromise, T0860)',
        'An unplanned firmware update',
        'Tamper or environmental alarms',
      ] },
      { p: `Review alerts jointly with process engineers, since valid communication can still produce incorrect physical behaviour.` },

      { h: 'Advanced Signal Integrity' },
      { p: `Methods such as sensor watermarking or small controlled signal distortions may help expose an attacker who replaces a real sensor with plausible fake readings, but they are advanced controls and any deliberate signal modification must be assessed for effects on quality and safety.` },

      { h: 'Capital Investment: Test Environment and Spares' },
      { p: `A test environment and spares lets firmware, configuration, calibration and communication changes be verified before deployment. A lifecycle programme should replace devices that lack security support, use fixed credentials, cannot disable services, cannot verify firmware or cannot be restored.` },
      { p: `Capital spending should first remove uncontrolled access and unsupported equipment, since monitoring adds little while devices remain exposed or unrecoverable.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Baseline device communication at gateways, switches and converters',
        'Alert on unknown masters and configuration outside maintenance windows',
        'Compare related measurements (valve vs position, pump vs flow)',
        'Track stale and frozen values, quality flags and heartbeats',
        'Compare running configurations against approved baselines on a schedule',
        'Include physical inspection in operator and maintenance rounds',
        'Review alerts jointly with process engineers',
      ] },
    ],
  },

  devicebackup: {
    blocks: [
      { h: 'Firmware and Supply-Chain Compromise' },
      { p: `Transmitters, drives, analyzers and relays may run complex firmware; malicious firmware can alter measurements, commands or communication (System Firmware, T0857; Module Firmware, T0839).` },
      { p: `Reloading a parameter file does not remove a firmware compromise, so recovery may require trusted firmware or device replacement. Devices should support authenticated updates, secure boot, protected configuration and removal of default credentials where feasible.` },

      { h: 'Default Credentials and Unused Interfaces' },
      { p: `Change default passwords, community strings, PINs and wireless keys where supported, unique at least by system, site or zone. Disable unused vendor and maintenance accounts, or restrict their services through the network. Protect legacy devices that cannot authenticate with locked cabinets, controlled maintenance access, allowlisting and monitored sessions.` },
      { p: `Disable local web, FTP, Telnet, SNMP, USB, serial, Bluetooth, Wi-Fi, NFC, memory-card and discovery interfaces that are not required, or block them at an upstream gateway. Replace insecure management protocols with secure alternatives, limit embedded web interfaces to approved systems, and enable wireless commissioning modes only during authorized work.` },

      { h: 'Firmware and Vulnerability Management' },
      { p: `Record firmware versions, review vendor and CISA advisories for installed models, and assess vulnerabilities by exposure, access paths, consequences and whether the function is enabled.` },
      { p: `Obtain firmware only from approved sources, verify signatures or hashes, and test on spare equipment (accuracy, actuator operation, communication, diagnostics, fail-safe behaviour, compatibility and rollback) before deployment. Where firmware cannot be updated, apply compensating controls. Favour devices with secure boot, signed firmware, authenticated updates, role-based access and defined support periods.` },

      { h: 'Backup and Recovery' },
      { p: `Retain everything needed to replace and recommission each important device: approved configuration, firmware and installation package, calibration records, range and scaling, I/O mapping, communication settings, recoverable keys, alarm and fail-safe settings, wiring drawings, commissioning procedure and vendor documentation, with at least one offline copy.` },
      { p: `Keep critical spares where lead times are long, and check them periodically for compatible firmware, battery condition, licences and vendor support.` },

      { h: 'Incident Response' },
      { p: `Begin with process and personnel safety. When compromise is suspected, determine whether the measurement is trustworthy, whether the actuator is in the commanded position, whether the process is stable, whether redundant instrumentation and the safety system remain available, whether the device can be isolated safely, and whether disconnecting it could create a hazard.` },
      { p: `Do not disconnect automatically without understanding the consequences. Containment may include blocking configuration traffic, removing an unauthorized tool, disabling remote access, changing credentials, switching to a redundant sensor, placing an actuator in a controlled local state, isolating the field segment, moving to manual operation or performing an approved safe shutdown. Preserve gateway logs, controller logs, captures, configurations, calibration records and installation photos where safe.` },

      { h: 'Recovery' },
      { p: `Use the approved commissioning baseline and verify device identity and serial, hardware revision, firmware integrity, range and scaling, calibration, alarm and diagnostic settings, communication address, authentication, allowed master, fail-safe state, wiring, local mode and correct process behaviour.` },
      { p: `Where firmware compromise is suspected, restoring parameters alone is insufficient; reprogram with trusted firmware or replace the hardware. Compare a restored sensor against a calibrated reference or redundant measurement, test a restored actuator through its range against independent feedback, and restore communication gradually (monitoring and read-only before configuration and full control). Recovery is complete only when both configuration and physical operation are confirmed.` },

      { h: 'Capital Investment: Secure-by-Design Replacement' },
      { p: `Secure-by-design replacement prioritizes devices that are externally reachable, unsupported, impossible to authenticate, unable to restrict configuration or hard to restore. Modern devices may add secure boot, signed firmware, authenticated updates, role-based access, encrypted communication, protected configuration and tamper detection.` },

      { h: 'Hardening Checklist' },
      { list: [
        'Record firmware versions and track vendor and CISA advisories',
        'Verify firmware signatures and test on spares before deployment',
        'Change default passwords, community strings, PINs and wireless keys',
        'Disable unused local and wireless interfaces or block them upstream',
        'Retain full recommissioning packages with at least one offline copy',
        'Keep critical spares checked for firmware, batteries and licences',
        'Replace devices that cannot authenticate, update or be restored',
      ] },

      { h: 'Resources' },
      { links: [
        { label: 'CISA Industrial Control Systems advisories', url: 'https://www.cisa.gov/news-events/cybersecurity-advisories?f%5B0%5D=advisory_type%3A93' },
        { label: 'The 3-2-1 backup rule and immutable backups against ransomware', url: search('3-2-1 backup rule immutable backup ransomware') },
      ] },
    ],
  },
};
